### ISSUE TITLE
file_rec/async returns no values

### ISSUE THREAD

**Issue by mr** [Shougo/unite.vim#1039]
When I run `:Unite file_rec/async` vim immediately opens the unite window with no results in it. It's worked before and it works on another machines with the same vim config. Any idea how to debug?

**Comment by Arlefreak** [comment]
I had this problem, and I fixed changing my vimrc ag config to:
```
" Using ag as recursive command.
		let g:unite_source_rec_async_command =
                \ ['ag', '--follow', '--nocolor', '--nogroup',
		\  '--hidden', '-g', '']
```
instead of:

```
  let g:unite_source_rec_async_command =
    \ ['ag', '--nocolor', '--nogroup', '-g', '""']
```

Also be sure to clear the cache <c-l>

**Comment by mr** [comment]
My settings used a string instead of a list. Using a list like you have suggested causes this error:

    Error detected while processing function unite#util#set_default:
    line    4:
    E706: Variable type mismatch for: g:unite_source_rec_async_command
    Press ENTER or type command to continue

I also tried using a string version of what you have there and I still have the same issue where nothing shows up. This problem persists when I remove everything from my vimrc aside from NeoBundle and Unite.

**Comment by Arlefreak** [comment]
Do you have the last version? The list parameter is relatively new

**Comment by mr** [comment]
Well I deleted the directory in my bundle directory and neobundle reinstalled it. So hopefully that would install the newest version, but I guess I can't be sure. I'll see if I can load it without neobundle

**Comment by Shougo** [comment]
I think it is same problem with #1034.
And you should read the issue template to report the issue.

https://github.com/Shougo/unite.vim/issues/584

I cannot reproduce it.

**Comment by Shougo** [comment]
No response.
